### ISSUE TITLE
Check why Ronny reacts to pasted Pictures with "Da soll ich jetzt 60 Tonnen drauf abstellen?!"

### ISSUE THREAD

**Issue by ldue** [krancorp/ronny-bot#21]
Debug posting a picture and let him do that in a defined way.
![image](https://cloud.githubusercontent.com/assets/18569303/23303337/d12a3ab2-fa93-11e6-90db-f2a34b119c3c.png)

"It's not a bug, it's a feature" - KranCorp

**Comment by watzkuh** [comment]
Ronny reacts to it since a trigger word is part of the image URL which is included in the message.
We will discuss if this is intended behaviour and react accordingly.
